#### __ДЗ по занятию 15.05.2023 + 18.05.2023__

In [1]:
import modules.classes as c
import time

#animal_lucy = c.Animal('Lucy', 'white')
#cat_tim = c.Cat('Tim', 'black')
#cat_sam = c.Cat('Sam', 'ginger')
#dog_ludwig = c.Dog('Ludwig', 'brown')
#horse_annabel = c.Horse('Annabel', 'ginger', 'Brumby')
#horse_danny = c.Horse('Danny', 'brown', height=170)

#animals = [animal, cat, another_cat, dog, horse, another_horse]
#for animal_el in animals:
#    print(f'I am {animal_el.name}. {animal_el.voice()}. My height is {animal_el.height} cm and my speed is {animal_el.speed} kmph')

dog_ludwig = c.Dog('Ludwig', 'brown')
dog_ani = c.Dog('Ani', 'white')
puppy = dog_ludwig + dog_ani
puppy.set_name('Lucky')
puppy.get_bigger()

cat_tim = c.Cat('Tim', 'black')
cat_liz = c.Cat('Liz', 'ginger')
kitty = cat_liz + cat_tim
kitty.set_name('Sam')
kitty.get_bigger()

horse_annabel = c.Horse('Annabel', 'ginger', 'Brumby')
horse_danny = c.Horse('Danny', 'brown', height=170)

animals = [dog_ludwig, dog_ani, puppy, cat_tim, cat_liz, kitty, horse_annabel, horse_danny]
animal_list = [lambda x = x: c.Doctor.get_examination(x) for x in animals]
c.Doctor.get_report(animal_list)

#### __ДЗ по занятию 11.05.2023__

In [ ]:
import modules.data_processing as dp
import modules.data_loading as dl

unsorted_list = [3, 7, 1, 2, 9, 8, 4]
sorted_list = dp.get_sorted_list(unsorted_list)

file_name = 'data\lesson1105.txt'
dl.write_list_in_file(dp.get_even_val(sorted_list), file_name, 'a')
dl.write_list_in_file(dp.get_even_ind_val(sorted_list), file_name, 'a')

#### __ДЗ по занятию 01.06.2023__

In [1]:
import numpy as np

In [7]:
sample_scalar = 20
sample_vector = np.array([1, 15, 86, 30])
vector_for_matrix = np.array([2, 86, 46, 76, 2, 6, 78, 1])

print(f"{sample_vector} {sample_vector.shape}\n")
sample_vector = np.expand_dims(sample_vector, -1)
print(f"{sample_vector} {sample_vector.shape}\n")

sample_matrix = vector_for_matrix.reshape(4, 2)
print(f"{sample_matrix} {sample_matrix.shape}")

[ 1 15 86 30] (4,)

[[ 1]
 [15]
 [86]
 [30]] (4, 1)

[[ 2 86]
 [46 76]
 [ 2  6]
 [78  1]] (4, 2)


##### **_Сложение_**

###### **Скаляр + матрица | вектор**

In [31]:
def sum_scalar(scalar: int, matrix: np.array)  -> list:
    return [[j + scalar for j in el] for el in matrix]

print(f"scalar: {sample_scalar}, vector: {sample_vector.tolist()}")
print(f"sum_scalar (scalar + vector): {sum_scalar(sample_scalar, sample_vector)}")
print(f"numpy (scalar + vector): {(sample_scalar + sample_vector).tolist()}")
print(f"sum_scalar == numpy is {sum_scalar(sample_scalar, sample_vector) == (sample_scalar + sample_vector).tolist()}\n")

print(f"scalar: {sample_scalar}, matrix: {sample_matrix.tolist()}")
print(f"sum_scalar (scalar + matrix): {sum_scalar(sample_scalar, sample_matrix)}")
print(f"numpy (scalar + matrix): {(sample_scalar + sample_matrix).tolist()}")
print(f"sum_scalar == numpy is {sum_scalar(sample_scalar, sample_matrix) == (sample_scalar + sample_matrix).tolist()}")

scalar: 20, vector: [[1], [15], [86], [30]]
sum_scalar (scalar + vector): [[21], [35], [106], [50]]
numpy (scalar + vector): [[21], [35], [106], [50]]
sum_scalar == numpy is True

scalar: 20, matrix: [[2, 86], [46, 76], [2, 6], [78, 1]]
sum_scalar (scalar + matrix): [[22, 106], [66, 96], [22, 26], [98, 21]]
numpy (scalar + matrix): [[22, 106], [66, 96], [22, 26], [98, 21]]
sum_scalar == numpy is True


###### **Вектор + матрица | вектор**

In [45]:
def sum_vector(vector: np.array, matrix: np.array) -> list:
    result = []
    for vector_row, matrix_row in zip(vector, matrix):
        result.append([row + vector_row[0] for row in matrix_row])
    return result
        
print(sum_vector(sample_vector, sample_vector))
print(f"sum_vector(vector + vector) == numpy is {sum_vector(sample_vector, sample_vector) == (sample_vector + sample_vector).tolist()}\n")
print(sum_vector(sample_vector, sample_matrix))
print(f"sum_vector(vector + matrix) == numpy is {sum_vector(sample_vector, sample_matrix) == (sample_vector + sample_matrix).tolist()}")


[[2], [30], [172], [60]]
sum_vector(vector + vector) == numpy is True

[[3, 87], [61, 91], [88, 92], [108, 31]]
sum_vector(vector + matrix) == numpy is True


###### **Матрица + матрица**

In [44]:
def sum_matrix(first_matrix: np.array, second_matrix: np.array) -> list:
    result = []
    for fm_row, sm_row in zip(first_matrix, second_matrix):
        result.append([fm_row_el + sm_row_el for fm_row_el, sm_row_el in zip(fm_row, sm_row)])
    return result

print(sum_matrix(sample_matrix, sample_matrix))
print(f"sum_matrix == numpy is {sum_matrix(sample_matrix, sample_matrix) == (sample_matrix + sample_matrix).tolist()}")

[[4, 172], [92, 152], [4, 12], [156, 2]]
sum_matrix == numpy is True


##### **_Транспонирование_**

In [140]:
def transp(matrix: np.array) -> np.array:
    result = []
    for row_i, row in enumerate(matrix):
        for i, el in enumerate(row):
            if row_i == 0:
                result.append([el])
            else:
                result[i].append(el)
    return np.array(result)

print(f"sample_matrix: {transp(sample_matrix)}")
print(f"transp == numpy is {transp(sample_matrix).tolist() == sample_matrix.T.tolist()}\n")

print(f"sample_vector: {transp(sample_vector)}")
print(f"transp == numpy is {transp(sample_vector).tolist() == sample_vector.T.tolist()}")

sample_matrix: [[ 2 46  2 78]
 [86 76  6  1]]
transp == numpy is True

sample_vector: [[ 1 15 86 30]]
transp == numpy is True


##### **_Умножение_**

###### **Скаляр * матрица | вектор**

In [119]:
def mlt_scalar(scalar: int, matrix: np.array) -> list:
    return [[el * scalar for el in row] for row in matrix]

print(mlt_scalar(sample_scalar, sample_matrix))
print(f"mlt_scalar(scalar * matrix) == numpy is {mlt_scalar(sample_scalar, sample_matrix) == np.dot(sample_scalar, sample_matrix).tolist()}\n")

print(mlt_scalar(sample_scalar, sample_vector))
print(f"mlt_scalar(scalar * vector) == numpy is {mlt_scalar(sample_scalar, sample_vector) == np.dot(sample_scalar, sample_vector).tolist()}\n")


[[40, 1720], [920, 1520], [40, 120], [1560, 20]]
mlt_scalar(scalar * matrix) == numpy is True

[[20], [300], [1720], [600]]
[[20], [300], [1720], [600]]
mlt_scalar(scalar * vector) == numpy is True



###### **Матрица | вектор * матрица | вектор**

In [88]:
fm = np.array([[1,5,7],
              [2,1,1],
              [3,2,9],
              [4,1,3]])
fv = np.array([1,2,3])
sm = np.array([[1,1],
               [2,2],
               [3,3]])

print(f"{fm.shape} * {fv.shape}")
print(np.dot(fm, fv))

(4, 3) * (3,)
[32  7 34 15]


In [139]:
def mlt_matrix(first_matrix: np.array, second_matrix: np.array) -> list:
    result = []
    try:
        first_matrix.shape[1]
    except IndexError:
        first_matrix = np.expand_dims(first_matrix, -1)

    try:
        second_matrix.shape[1]
    except IndexError:
        second_matrix = np.expand_dims(second_matrix, -1)

    for fm_row_ind, fm_row in enumerate(first_matrix):
        for i in range(second_matrix.shape[1]):
            sm_col = second_matrix[:, i]
            v = 0
            for fm_el, sm_el in zip(fm_row, sm_col):
                v += fm_el * sm_el
            if i == 0:
                result.append([v])
            else:
                result[fm_row_ind].append(v)
        
    return result


print(f"matrix * vector: {mlt_matrix(fm, fv)}")
print(np.dot(fm, fv))
print(f"mlt_matrix(matrix * vector) == numpy is {mlt_matrix(fm, fv) == np.expand_dims(np.dot(fm, fv), -1).tolist()}\n")

print(f"matrix * matrix: {mlt_matrix(fm, sm)}")
print(f"mlt_matrix(matrix * matrix) == numpy is {mlt_matrix(fm, sm) == np.dot(fm, sm).tolist()}")

matrix * vector: [[32], [7], [34], [15]]
[32  7 34 15]
mlt_matrix(matrix * vector) == numpy is True

matrix * matrix: [[32, 32], [7, 7], [34, 34], [15, 15]]
mlt_matrix(matrix * matrix) == numpy is True


In [137]:
print(f"{sample_matrix.shape} {sample_vector.shape}")
print(f"numpy sample_matrix on sample_vector = {np.dot(sample_matrix.T, sample_vector).tolist()}")
print(f"mlt_matrix sample_matrix on sample_vector = {mlt_matrix(transp(sample_matrix), sample_vector)}")

(4, 2) (4, 1)
numpy sample_matrix on sample_vector = [[3204], [1772]]
mlt_matrix sample_matrix on sample_vector = [[3204], [1772]]
